import 'package:flutter/material.dart';import 'package:yosif_s_application3/core/app_export.dart';import 'package:yosif_s_application3/widgets/custom_elevated_button.dart';class Iphone14FiveScreen extends StatelessWidget {const Iphone14FiveScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onPrimary, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 45.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Text("Flash?", style: theme.textTheme.headlineSmall)), SizedBox(height: 20.v), _buildFlashDescription(context), SizedBox(height: 30.v), Padding(padding: EdgeInsets.only(left: 27.h), child: Text("File info:", style: CustomTextStyles.titleLargeUrbanistSemiBold)), SizedBox(height: 29.v), Container(width: 204.h, margin: EdgeInsets.only(left: 27.h), child: Text("Originates from:\nNot known\n\nFile size:\n78,5MB\n\nCreation date:\nToday, 10 mins ago", maxLines: 8, overflow: TextOverflow.ellipsis, style: theme.textTheme.headlineSmall)), SizedBox(height: 5.v)])), bottomNavigationBar: _buildFlashButtons(context))); } 
/// Section Widget
Widget _buildFlashDescription(BuildContext context) { return Container(margin: EdgeInsets.only(left: 9.h), padding: EdgeInsets.symmetric(horizontal: 25.h, vertical: 29.v), decoration: AppDecoration.fillGray80001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder21), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 6.v), SizedBox(width: 309.h, child: Text("Do you wish to flash the file “AmeOS SSdraivrer jailbreak”?\nIf you continue this cannot be undo unless the flashing item supports deleting with Ame Vault.", maxLines: 5, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleLargeUrbanistSemiBold))])); } 
/// Section Widget
Widget _buildFlashButtons(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 27.h, right: 27.h, bottom: 28.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomElevatedButton(height: 58.v, width: 163.h, text: "Flash", buttonStyle: CustomButtonStyles.fillGray, buttonTextStyle: CustomTextStyles.titleLargeUrbanistSemiBold, onPressed: () {onTapFlash(context);}), CustomElevatedButton(height: 58.v, width: 163.h, text: "Cancel", margin: EdgeInsets.only(left: 10.h), buttonStyle: CustomButtonStyles.fillGray, buttonTextStyle: CustomTextStyles.titleLargeUrbanistSemiBold, onPressed: () {onTapCancel(context);})])); } 
/// Navigates to the iphone14EightScreen when the action is triggered.
onTapFlash(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone14EightScreen); } 
/// Navigates to the iphone14FourScreen when the action is triggered.
onTapCancel(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone14FourScreen); } 
 }
