import 'package:flutter/material.dart';import 'package:yosif_s_application3/core/app_export.dart';import 'package:yosif_s_application3/widgets/app_bar/appbar_leading_image.dart';import 'package:yosif_s_application3/widgets/app_bar/appbar_subtitle_three.dart';import 'package:yosif_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:yosif_s_application3/widgets/custom_elevated_button.dart';import 'package:yosif_s_application3/widgets/custom_icon_button.dart';class Iphone14198Screen extends StatelessWidget {const Iphone14198Screen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, appBar: _buildAppBar(context), body: Container(width: SizeUtils.width, height: SizeUtils.height, decoration: BoxDecoration(gradient: LinearGradient(begin: Alignment(0.5, 0), end: Alignment(0.5, 1), colors: [appTheme.gray600, appTheme.gray80007, appTheme.gray90003])), child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 47.v), child: Column(children: [SizedBox(height: 9.v), _buildFrameColumn(context), SizedBox(height: 32.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 60.h), child: Row(children: [CustomElevatedButton(height: 40.v, width: 88.h, text: "Play", leftIcon: Container(margin: EdgeInsets.only(right: 6.h), child: CustomImageView(imagePath: ImageConstant.imgPlayarrow, height: 21.adaptSize, width: 21.adaptSize)), buttonStyle: CustomButtonStyles.fillGrayTL20, buttonTextStyle: CustomTextStyles.bodyMediumOnPrimaryContainer15, onPressed: () {onTapPlay(context);}), GestureDetector(onTap: () {onTapFrame(context);}, child: Container(width: 76.h, margin: EdgeInsets.only(left: 31.h, top: 9.v, bottom: 9.v), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgUser, height: 21.adaptSize, width: 21.adaptSize), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("Shuffle", style: CustomTextStyles.bodyMediumOnPrimaryContainer15))])))]))), SizedBox(height: 32.v), CustomImageView(imagePath: ImageConstant.imgFrame38308, height: 24.v, width: 192.h), SizedBox(height: 46.v), Align(alignment: Alignment.centerLeft, child: Text("ALSO IN “MR MORALE & THE BIG STEPPER”", style: CustomTextStyles.bodySmall_1)), SizedBox(height: 16.v), _buildFrameRow(context, dynamicText: "Die Hard", dynamicText1: "Kendrick Lamar"), SizedBox(height: 24.v), _buildFrameRow(context, dynamicText: "Rich Spirit", dynamicText1: "Kendrick Lamar")]))), bottomNavigationBar: _buildNavigationBar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 53.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 29.h, top: 13.v, bottom: 18.v), onTap: () {onTapArrowLeft(context);}), title: AppbarSubtitleThree(text: "Mr Morale & The Big Stepper", margin: EdgeInsets.only(left: 20.h))); } 
/// Section Widget
Widget _buildFrameColumn(BuildContext context) { return Column(children: [CustomImageView(imagePath: ImageConstant.imgRectangle34773398x98, height: 160.adaptSize, width: 160.adaptSize, radius: BorderRadius.circular(12.h)), SizedBox(height: 25.v), Text("N95", style: CustomTextStyles.titleLargeOnPrimaryContainer_1), SizedBox(height: 7.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgThumbsUpOnprimarycontainer, height: 16.adaptSize, width: 16.adaptSize), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("Kendrick Lamar • 2022", style: CustomTextStyles.bodySmallOnPrimaryContainer_1))])]); } 
/// Section Widget
Widget _buildNavigationBar(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 51.h, right: 57.h, bottom: 12.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgIconContainerOnprimarycontainer, height: 24.adaptSize, width: 24.adaptSize, radius: BorderRadius.circular(12.h)), Padding(padding: EdgeInsets.only(top: 4.v), child: Text("Home", style: CustomTextStyles.bodySmallOnPrimaryContainer_2))]), CustomImageView(imagePath: ImageConstant.imgRewind, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 10.v, bottom: 9.v)), CustomImageView(imagePath: ImageConstant.imgIconContainer, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 10.v, bottom: 9.v))])); } 
/// Common widget
Widget _buildFrameRow(BuildContext context, {required String dynamicText, required String dynamicText1, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(dynamicText, style: CustomTextStyles.titleLargeOnPrimaryContainer_1.copyWith(color: theme.colorScheme.onPrimaryContainer.withOpacity(0.75))), SizedBox(height: 2.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgThumbsUpOnprimarycontainer, height: 16.adaptSize, width: 16.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h), child: Text(dynamicText1, style: CustomTextStyles.bodySmallOnPrimaryContainer_1.copyWith(color: theme.colorScheme.onPrimaryContainer.withOpacity(0.65))))])])), Padding(padding: EdgeInsets.only(bottom: 5.v), child: CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, padding: EdgeInsets.all(9.h), decoration: IconButtonStyleHelper.fillGray, child: CustomImageView(imagePath: ImageConstant.imgPlayarrow)))]); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the iphone14202Screen when the action is triggered.
onTapPlay(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone14202Screen); } 
/// Navigates to the iphone14202Screen when the action is triggered.
onTapFrame(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone14202Screen); } 
 }
