import 'package:flutter/material.dart';import 'package:yosif_s_application3/core/app_export.dart';import 'package:yosif_s_application3/widgets/custom_elevated_button.dart';class Iphone14SixScreen extends StatelessWidget {const Iphone14SixScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onPrimary, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 28.h, vertical: 40.v), child: Column(children: [_buildFlashingSection(context), SizedBox(height: 96.v), CustomImageView(imagePath: ImageConstant.imgGroup38323, height: 41.v, width: 283.h), SizedBox(height: 65.v), Text("FILE HAS BEEN FLASHED", style: CustomTextStyles.titleLargeUrbanist), SizedBox(height: 5.v)])), bottomNavigationBar: _buildRestartSection(context))); } 
/// Section Widget
Widget _buildFlashingSection(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 12.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Flashing...", style: theme.textTheme.headlineSmall), SizedBox(height: 28.v), Container(width: 317.h, margin: EdgeInsets.only(left: 5.h), padding: EdgeInsets.symmetric(horizontal: 26.h, vertical: 32.v), decoration: AppDecoration.fillGray80001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 17.v), Container(width: 227.h, margin: EdgeInsets.only(right: 37.h), child: Text("flashing file..\n\nSubscribe to SSdraivrer!\n\nUnzipping to AmeCore\n320Files please wait...\n\n//ame//system/device\n//ame//system/os\n\ndone!  23.05.34 seconds", maxLines: 11, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleMediumRedHatMono))]))])); } 
/// Section Widget
Widget _buildRestartSection(BuildContext context) { return CustomElevatedButton(height: 58.v, text: "Restart", margin: EdgeInsets.only(left: 32.h, right: 32.h, bottom: 28.v), buttonStyle: CustomButtonStyles.fillGray, buttonTextStyle: CustomTextStyles.titleLargeUrbanistSemiBold, onPressed: () {onTapRestartSection(context);}); } 
/// Navigates to the iphone14FourScreen when the action is triggered.
onTapRestartSection(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone14FourScreen); } 
 }
