import 'package:flutter/material.dart';import 'package:yosif_s_application3/core/app_export.dart';import 'package:yosif_s_application3/widgets/app_bar/appbar_leading_image.dart';import 'package:yosif_s_application3/widgets/app_bar/appbar_subtitle.dart';import 'package:yosif_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:yosif_s_application3/widgets/custom_elevated_button.dart';import 'package:yosif_s_application3/widgets/custom_icon_button.dart';class Iphone14196Screen extends StatelessWidget {const Iphone14196Screen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, appBar: _buildAppBar(context), body: Container(width: SizeUtils.width, height: SizeUtils.height, decoration: BoxDecoration(gradient: LinearGradient(begin: Alignment(0.5, 0.19), end: Alignment(0.5, 0.27), colors: [appTheme.pinkA70033, appTheme.purple60033])), child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 46.v), child: Column(children: [SizedBox(height: 11.v), CustomImageView(imagePath: ImageConstant.imgRectangle347733, height: 160.adaptSize, width: 160.adaptSize, radius: BorderRadius.circular(12.h)), SizedBox(height: 25.v), Text("Just Wanna Rock", style: CustomTextStyles.titleLargeOnPrimaryContainer_1), SizedBox(height: 7.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgThumbsUpOnprimarycontainer, height: 16.adaptSize, width: 16.adaptSize), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("Lil Uzi Vert • 2022", style: CustomTextStyles.bodySmallOnPrimaryContainer_1))]), SizedBox(height: 32.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 60.h, right: 76.h), child: Row(children: [CustomElevatedButton(height: 40.v, width: 88.h, text: "Play", leftIcon: Container(margin: EdgeInsets.only(right: 6.h), child: CustomImageView(imagePath: ImageConstant.imgPlayarrow, height: 21.adaptSize, width: 21.adaptSize)), buttonStyle: CustomButtonStyles.fillBlueGrayTL20, buttonTextStyle: CustomTextStyles.bodyMediumOnPrimaryContainer15), Spacer(), CustomImageView(imagePath: ImageConstant.imgUser, height: 21.adaptSize, width: 21.adaptSize, margin: EdgeInsets.symmetric(vertical: 9.v)), Padding(padding: EdgeInsets.only(left: 6.h, top: 9.v, bottom: 10.v), child: Text("Shuffle", style: CustomTextStyles.bodyMediumOnPrimaryContainer15))]))), SizedBox(height: 32.v), CustomImageView(imagePath: ImageConstant.imgFrame38308, height: 24.v, width: 192.h), SizedBox(height: 46.v), _buildAlsoInGraduation(context)]))), bottomNavigationBar: _buildNavigationBar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 53.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 29.h, top: 15.v, bottom: 16.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitle(text: "Just Wanna Rock")); } 
/// Section Widget
Widget _buildAlsoInGraduation(BuildContext context) { return Column(children: [Align(alignment: Alignment.centerLeft, child: Text("ALSO IN “GRADUATION”", style: CustomTextStyles.bodySmall_1)), SizedBox(height: 16.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Stronger", style: CustomTextStyles.titleLargeOnPrimaryContainer_1), SizedBox(height: 2.v), _buildFrame(context, text: "Kanye West ")])), Padding(padding: EdgeInsets.only(bottom: 5.v), child: CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, padding: EdgeInsets.all(9.h), decoration: IconButtonStyleHelper.fillBlueGrayTL20, child: CustomImageView(imagePath: ImageConstant.imgPlayarrow)))]), SizedBox(height: 22.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(children: [Text("Good Life", style: CustomTextStyles.titleLargeOnPrimaryContainer_1), SizedBox(height: 4.v), _buildFrame(context, text: "Kanye West ")]), Padding(padding: EdgeInsets.only(bottom: 5.v), child: CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, padding: EdgeInsets.all(9.h), decoration: IconButtonStyleHelper.fillBlueGrayTL20, child: CustomImageView(imagePath: ImageConstant.imgPlayarrow)))])]); } 
/// Section Widget
Widget _buildNavigationBar(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 51.h, right: 57.h, bottom: 12.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [GestureDetector(onTap: () {onTapSegment1(context);}, child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgIconContainerOnprimarycontainer, height: 24.adaptSize, width: 24.adaptSize, radius: BorderRadius.circular(12.h)), Padding(padding: EdgeInsets.only(top: 4.v), child: Text("Home", style: CustomTextStyles.bodySmallOnPrimaryContainer_2))])), CustomImageView(imagePath: ImageConstant.imgRewind, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 10.v, bottom: 9.v)), CustomImageView(imagePath: ImageConstant.imgIconContainer, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 10.v, bottom: 9.v))])); } 
/// Common widget
Widget _buildFrame(BuildContext context, {required String text, }) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgThumbsUpOnprimarycontainer, height: 16.adaptSize, width: 16.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h), child: Text(text, style: CustomTextStyles.bodySmallOnPrimaryContainer_1.copyWith(color: theme.colorScheme.onPrimaryContainer.withOpacity(0.65))))]); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the iphone14194Screen when the action is triggered.
onTapSegment1(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone14194Screen); } 
 }
