import '../iphone_14_194_screen/widgets/justwannarock_item_widget.dart';import '../iphone_14_194_screen/widgets/userprofile1_item_widget.dart';import 'package:flutter/material.dart';import 'package:yosif_s_application3/core/app_export.dart';import 'package:yosif_s_application3/presentation/iphone_14_106_page/iphone_14_106_page.dart';import 'package:yosif_s_application3/widgets/app_bar/appbar_subtitle.dart';import 'package:yosif_s_application3/widgets/app_bar/appbar_trailing_image.dart';import 'package:yosif_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:yosif_s_application3/widgets/custom_bottom_bar.dart';
// ignore_for_file: must_be_immutable
class Iphone14194Screen extends StatelessWidget {Iphone14194Screen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 34.v), child: Column(children: [SizedBox(height: 8.v), Expanded(child: SingleChildScrollView(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildWeThinkYoull(context), SizedBox(height: 38.v), Padding(padding: EdgeInsets.only(left: 29.h), child: Text("CONTINUE LISTENING", style: CustomTextStyles.bodySmall_1)), SizedBox(height: 27.v), _buildJustWannaRock(context), SizedBox(height: 32.v), Padding(padding: EdgeInsets.only(left: 29.h), child: Text("ARTISTS YOU LOVE", style: CustomTextStyles.bodySmall_1)), SizedBox(height: 23.v), _buildUserName(context)])))])), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(title: AppbarSubtitle(text: "Hey there!", margin: EdgeInsets.only(left: 29.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgContrast, margin: EdgeInsets.fromLTRB(29.h, 8.v, 29.h, 11.v))]); } 
/// Section Widget
Widget _buildWeThinkYoull(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 28.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 1.h), child: Text("WE THINK YOU’LL LIKE", style: CustomTextStyles.bodySmall_1)), SizedBox(height: 23.v), Container(height: 157.v, width: 333.h, margin: EdgeInsets.only(left: 1.h), child: Stack(alignment: Alignment.bottomLeft, children: [CustomImageView(imagePath: ImageConstant.imgRectangle347731, height: 157.v, width: 333.h, radius: BorderRadius.circular(12.h), alignment: Alignment.center, onTap: () {onTapImgImage(context);}), Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(left: 19.h, bottom: 16.v), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Flashing Lights", style: theme.textTheme.titleLarge), SizedBox(height: 2.v), Text("Kanye West", style: CustomTextStyles.bodySmallOnPrimaryContainer_3)])))]))])); } 
/// Section Widget
Widget _buildJustWannaRock(BuildContext context) { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 145.v, child: ListView.separated(padding: EdgeInsets.only(left: 29.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 22.h);}, itemCount: 4, itemBuilder: (context, index) {return JustwannarockItemWidget(onTapImgImage: () {onTapImgImage(context);});}))); } 
/// Section Widget
Widget _buildUserName(BuildContext context) { return SizedBox(height: 212.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topRight, child: Row(mainAxisAlignment: MainAxisAlignment.end, mainAxisSize: MainAxisSize.min, children: [Expanded(child: SizedBox(height: 129.v, child: ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 22.h);}, itemCount: 3, itemBuilder: (context, index) {return Userprofile1ItemWidget();}))), Padding(padding: EdgeInsets.only(left: 22.h), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgEllipse13021, height: 100.adaptSize, width: 100.adaptSize, radius: BorderRadius.circular(50.h)), SizedBox(height: 13.v), Text("Kendrick Lamar", style: theme.textTheme.bodySmall)]))])), Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 152.h, vertical: 12.v), decoration: AppDecoration.outlineBlack9005, child: Divider()))])); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Image1: return AppRoutes.iphone14106Page; case BottomBarEnum.Image59: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.iphone14106Page: return Iphone14106Page(); default: return DefaultWidget();} } 
/// Navigates to the iphone14197Screen when the action is triggered.
onTapImgImage(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone14195Screen); } 
 }
