import 'package:flutter/material.dart';import 'package:yosif_s_application3/core/app_export.dart';import 'package:yosif_s_application3/widgets/custom_floating_button.dart';import 'package:yosif_s_application3/widgets/custom_icon_button.dart';class Iphone14128Bottomsheet extends StatelessWidget {const Iphone14128Bottomsheet({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SizedBox(height: SizeUtils.height, width: double.maxFinite, child: Stack(alignment: Alignment.bottomRight, children: [Align(alignment: Alignment.center, child: Column(mainAxisSize: MainAxisSize.min, children: [_buildShareToSection(context)])), _buildFloatingActionButtonSection(context)])); } 
/// Section Widget
Widget _buildShareToSection(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 26.h, vertical: 25.v), decoration: AppDecoration.fillGray100.copyWith(borderRadius: BorderRadiusStyle.customBorderTL40), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.centerRight, child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Text("Share to", style: CustomTextStyles.titleLargeGray90005), Padding(padding: EdgeInsets.only(left: 105.h), child: CustomIconButton(height: 25.adaptSize, width: 25.adaptSize, padding: EdgeInsets.all(1.h), decoration: IconButtonStyleHelper.fillBlueGray, onTap: () {onTapBtnClose(context);}, child: CustomImageView(imagePath: ImageConstant.imgClose)))])), SizedBox(height: 24.v), Container(margin: EdgeInsets.symmetric(horizontal: 8.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 13.v), decoration: AppDecoration.fillBlue5002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder21), child: Row(mainAxisSize: MainAxisSize.max, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, padding: EdgeInsets.all(8.h), decoration: IconButtonStyleHelper.fillBlue, child: CustomImageView(imagePath: ImageConstant.imgThumbsUp))), Padding(padding: EdgeInsets.only(left: 15.h, top: 3.v, bottom: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Theme", style: theme.textTheme.bodyLarge), SizedBox(height: 1.v), Text("1.3 MB", style: CustomTextStyles.bodySmallGray90005)]))])), SizedBox(height: 39.v), Padding(padding: EdgeInsets.only(left: 13.h, right: 26.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.only(bottom: 15.v), child: Column(children: [CustomIconButton(height: 56.adaptSize, width: 56.adaptSize, padding: EdgeInsets.all(16.h), decoration: IconButtonStyleHelper.fillBlueTL28, child: CustomImageView(imagePath: ImageConstant.imgInstagram)), SizedBox(height: 11.v), Text("Your laptop", style: theme.textTheme.bodyMedium)])), Spacer(flex: 45), Padding(padding: EdgeInsets.only(bottom: 15.v), child: Column(children: [CustomIconButton(height: 56.adaptSize, width: 56.adaptSize, padding: EdgeInsets.all(16.h), decoration: IconButtonStyleHelper.fillBlueTL28, child: CustomImageView(imagePath: ImageConstant.imgMinimize)), SizedBox(height: 9.v), Text("Your tablet", style: theme.textTheme.bodyMedium)])), Spacer(flex: 55), Container(width: 46.h, margin: EdgeInsets.only(top: 65.v, right: 5.h), child: Text("Google\nPixel 7", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodyMedium))])), SizedBox(height: 30.v), Align(alignment: Alignment.center, child: Text("You’re visible as Ame9OS device", style: CustomTextStyles.bodySmallBluegray90072))])); } 
/// Section Widget
Widget _buildFloatingActionButtonSection(BuildContext context) { return CustomFloatingButton(height: 56, width: 56, backgroundColor: appTheme.blue5002, decoration: FloatingButtonStyleHelper.fillBlue, alignment: Alignment.bottomRight, child: CustomImageView(imagePath: ImageConstant.imgMinimizeGray90005, height: 28.0.v, width: 28.0.h)); } 

/// Navigates back to the previous screen.
onTapBtnClose(BuildContext context) { Navigator.pop(context); } 
 }
