import 'package:flutter/material.dart';import 'package:yosif_s_application3/core/app_export.dart';class SeturenviromentThreeScreen extends StatelessWidget {const SeturenviromentThreeScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.blue5001, body: SizedBox(width: double.maxFinite, child: SingleChildScrollView(child: Column(children: [SizedBox(width: double.maxFinite, child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 484.v, width: 336.h, margin: EdgeInsets.only(bottom: 68.v), child: Stack(alignment: Alignment.bottomRight, children: [_buildSetYourEnvironmentStack(context), CustomImageView(imagePath: ImageConstant.imgGroup38295, height: 184.v, width: 262.h, alignment: Alignment.bottomRight, margin: EdgeInsets.only(right: 10.h), onTap: () {onTapImgImage(context);})])), CustomImageView(imagePath: ImageConstant.imgRectangle3477042, height: 79.v, width: 53.h, margin: EdgeInsets.only(top: 473.v))])), SizedBox(height: 51.v), Align(alignment: Alignment.centerRight, child: SizedBox(height: 523.v, width: 250.h, child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.imgStar158, height: 523.v, width: 250.h, radius: BorderRadius.circular(53.h), alignment: Alignment.center), Align(alignment: Alignment.topLeft, child: GestureDetector(onTap: () {onTapThree(context);}, child: Container(margin: EdgeInsets.only(left: 13.h), padding: EdgeInsets.symmetric(horizontal: 23.h), decoration: AppDecoration.gradientCyanToBlack.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Container(height: 9.v, width: 30.h, decoration: BoxDecoration(color: appTheme.blue50, borderRadius: BorderRadius.only(topLeft: Radius.circular(1.h), topRight: Radius.circular(1.h), bottomLeft: Radius.circular(4.h), bottomRight: Radius.circular(4.h)))))))])))]))))); } 
/// Section Widget
Widget _buildSetYourEnvironmentStack(BuildContext context) { return Align(alignment: Alignment.topCenter, child: SizedBox(height: 386.v, width: 336.h, child: Stack(alignment: Alignment.topRight, children: [CustomImageView(imagePath: ImageConstant.imgStar168, height: 386.v, width: 336.h, radius: BorderRadius.circular(73.h), alignment: Alignment.center), Align(alignment: Alignment.topRight, child: Padding(padding: EdgeInsets.only(top: 119.v, right: 5.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 187.h, child: RichText(text: TextSpan(children: [TextSpan(text: "Set your\n", style: CustomTextStyles.headlineLargeBlack900), TextSpan(text: "environment", style: CustomTextStyles.headlineLargeBlack900Bold)]), textAlign: TextAlign.left)), SizedBox(height: 11.v), Text("Depends if you’re on a phone or a PC", style: CustomTextStyles.bodyLargeBlack90018)])))]))); } 
/// Navigates to the seturenviromentTwoScreen when the action is triggered.
onTapImgImage(BuildContext context) { Navigator.pushNamed(context, AppRoutes.seturenviromentTwoScreen); } 
/// Navigates to the iphone14175Screen when the action is triggered.
onTapThree(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone14175Screen); } 
 }
