import '../iphone_14_eightythree_screen/widgets/textvalue_item_widget.dart';import 'package:flutter/material.dart';import 'package:yosif_s_application3/core/app_export.dart';class Iphone14EightythreeScreen extends StatelessWidget {const Iphone14EightythreeScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onPrimaryContainer.withOpacity(1), body: SizedBox(width: 388.h, child: Column(children: [SizedBox(height: 123.v), Expanded(child: SingleChildScrollView(child: Column(children: [Text("00:00:10", style: CustomTextStyles.displayLargeProductSansGray90005), SizedBox(height: 48.v), _buildTimeSection(context), SizedBox(height: 126.v), Padding(padding: EdgeInsets.symmetric(horizontal: 55.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgIconContainerGray90005, height: 24.adaptSize, width: 24.adaptSize, radius: BorderRadius.circular(12.h), margin: EdgeInsets.only(top: 10.v, bottom: 9.v), onTap: () {onTapImgIconContainer(context);}), Column(children: [CustomImageView(imagePath: ImageConstant.imgTelevisionGray90005, height: 24.adaptSize, width: 24.adaptSize), SizedBox(height: 4.v), Text("Timer", style: CustomTextStyles.bodySmallGray90005_1)]), CustomImageView(imagePath: ImageConstant.imgClockGray90005, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 10.v, bottom: 9.v), onTap: () {onTapImgClock(context);})])), SizedBox(height: 12.v), _buildVectorSection(context)])))])))); } 
/// Section Widget
Widget _buildTimeSection(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 54.h), child: Column(children: [GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 78.v, crossAxisCount: 3, mainAxisSpacing: 23.h, crossAxisSpacing: 23.h), physics: NeverScrollableScrollPhysics(), itemCount: 9, itemBuilder: (context, index) {return TextvalueItemWidget();}), SizedBox(height: 28.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(height: 77.adaptSize, width: 77.adaptSize, padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 22.v), decoration: AppDecoration.outlineGrayE.copyWith(borderRadius: BorderRadiusStyle.roundedBorder40), child: CustomImageView(imagePath: ImageConstant.imgCloseGray90005, height: 28.adaptSize, width: 28.adaptSize, alignment: Alignment.center)), Container(padding: EdgeInsets.symmetric(horizontal: 25.h, vertical: 16.v), decoration: AppDecoration.outlineGrayE.copyWith(borderRadius: BorderRadiusStyle.roundedBorder40), child: Text("0", style: CustomTextStyles.headlineLargeGray90005)), GestureDetector(onTap: () {onTapPlayArrow(context);}, child: Container(height: 77.adaptSize, width: 77.adaptSize, padding: EdgeInsets.all(23.h), decoration: AppDecoration.outlineGrayE.copyWith(borderRadius: BorderRadiusStyle.roundedBorder40), child: CustomImageView(imagePath: ImageConstant.imgPlayArrowGray90005, height: 28.adaptSize, width: 28.adaptSize, alignment: Alignment.center)))])])); } 
/// Section Widget
Widget _buildVectorSection(BuildContext context) { return GestureDetector(onTap: () {onTapVectorSection(context);}, child: Container(padding: EdgeInsets.symmetric(horizontal: 150.h, vertical: 12.v), decoration: AppDecoration.outlineBlack9007, child: Divider(color: appTheme.black900))); } 
/// Navigates to the iphone14149Screen when the action is triggered.
onTapPlayArrow(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone14149Screen); } 
/// Navigates to the iphone14SeventyfourScreen when the action is triggered.
onTapImgIconContainer(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone14SeventyfourScreen); } 
/// Navigates to the iphone14150Screen when the action is triggered.
onTapImgClock(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone14150Screen); } 
/// Navigates to the mainHomeScreenTwoScreen when the action is triggered.
onTapVectorSection(BuildContext context) { Navigator.pushNamed(context, AppRoutes.mainHomeScreenTwoScreen); } 
 }
