import 'package:flutter/material.dart';import 'package:yosif_s_application3/core/app_export.dart';import 'package:yosif_s_application3/widgets/custom_icon_button.dart';class Iphone14150Screen extends StatelessWidget {const Iphone14150Screen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onPrimaryContainer.withOpacity(1), body: SizedBox(width: 388.h, child: Column(children: [SizedBox(height: 325.v), Expanded(child: SingleChildScrollView(child: Column(children: [Text("00:00:00", style: CustomTextStyles.displayLargeProductSansGray90005), SizedBox(height: 183.v), CustomIconButton(height: 77.adaptSize, width: 77.adaptSize, padding: EdgeInsets.all(24.h), decoration: IconButtonStyleHelper.outlineBlackTL38, child: CustomImageView(imagePath: ImageConstant.imgPlayArrowGray9000277x77)), SizedBox(height: 104.v), Padding(padding: EdgeInsets.only(left: 55.h, right: 39.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgClockGray9000524x24, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 10.v), onTap: () {onTapImgClock(context);}), Spacer(flex: 54), CustomImageView(imagePath: ImageConstant.imgLock, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 10.v), onTap: () {onTapImgLock(context);}), Spacer(flex: 45), Column(children: [CustomImageView(imagePath: ImageConstant.imgClockGray90005, height: 24.adaptSize, width: 24.adaptSize), SizedBox(height: 5.v), Text("Stopwatch", style: CustomTextStyles.bodySmallGray90005_1)])])), SizedBox(height: 11.v), _buildVectorLine(context)])))])))); } 
/// Section Widget
Widget _buildVectorLine(BuildContext context) { return GestureDetector(onTap: () {onTapVectorLine(context);}, child: Container(padding: EdgeInsets.symmetric(horizontal: 150.h, vertical: 12.v), decoration: AppDecoration.outlineBlack9007, child: Divider(color: appTheme.black900))); } 
/// Navigates to the iphone14SeventyfourScreen when the action is triggered.
onTapImgClock(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone14SeventyfourScreen); } 
/// Navigates to the iphone14EightythreeScreen when the action is triggered.
onTapImgLock(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone14EightythreeScreen); } 
/// Navigates to the mainHomeScreenTwoScreen when the action is triggered.
onTapVectorLine(BuildContext context) { Navigator.pushNamed(context, AppRoutes.mainHomeScreenTwoScreen); } 
 }
