import 'package:flutter/material.dart';import 'package:yosif_s_application3/core/app_export.dart';import 'package:yosif_s_application3/widgets/app_bar/appbar_leading_image.dart';import 'package:yosif_s_application3/widgets/app_bar/appbar_subtitle_one.dart';import 'package:yosif_s_application3/widgets/app_bar/custom_app_bar.dart';class Iphone14243Screen extends StatelessWidget {const Iphone14243Screen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onPrimaryContainer.withOpacity(1), appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 28.h, vertical: 30.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildView(context), SizedBox(height: 29.v), Container(width: 307.h, margin: EdgeInsets.only(left: 1.h, right: 25.h), child: Text("You haven’t been responding to me...\n\nAre you okay or\nare you busy?\n\nIf you’re not dead then give me a ring!\n\nOh yea your phone can’t make phone calls 😹\nImagine spending £899 on a phone that looks like it was from a cartoon 💀\n\nI’m so glad I’m NORMAL and use an iPhone\nYou make the worst decisions smh", maxLines: 13, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium)), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 144.v, leadingWidth: 53.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftGray90005, margin: EdgeInsets.only(left: 29.h, top: 7.v, bottom: 32.v), onTap: () {onTapArrowLeft(context);}), title: AppbarSubtitleOne(text: "Hey there! I’m still stuck in the rubber r...", margin: EdgeInsets.only(left: 28.h))); } 
/// Section Widget
Widget _buildView(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 1.h), child: Row(children: [Container(height: 42.adaptSize, width: 42.adaptSize, decoration: BoxDecoration(color: appTheme.blue5002, borderRadius: BorderRadius.circular(21.h))), Padding(padding: EdgeInsets.only(left: 20.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 87.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("Person", style: theme.textTheme.bodyLarge), Padding(padding: EdgeInsets.only(top: 3.v), child: Text("19:28", style: CustomTextStyles.bodySmallGray90005_2))])), SizedBox(height: 8.v), Text("to me", style: CustomTextStyles.bodySmallGray90005_2)])), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowDown, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 9.v)), CustomImageView(imagePath: ImageConstant.imgNotification, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 12.h, top: 9.v, bottom: 9.v))])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
