import 'package:flutter/material.dart';import 'package:yosif_s_application3/core/app_export.dart';class Iphone14233Screen extends StatelessWidget {const Iphone14233Screen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, body: Container(width: SizeUtils.width, height: SizeUtils.height, decoration: BoxDecoration(gradient: LinearGradient(begin: Alignment(0.5, 0), end: Alignment(0.5, 1), colors: [appTheme.indigo40001, appTheme.indigo400, appTheme.pink10001])), child: SizedBox(height: 843.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SingleChildScrollView(child: SizedBox(height: 843.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgArrowUp, height: 7.v, width: 15.h, alignment: Alignment.bottomCenter, margin: EdgeInsets.only(bottom: 176.v)), Align(alignment: Alignment.center, child: Container(margin: EdgeInsets.symmetric(horizontal: 28.h), decoration: BoxDecoration(image: DecorationImage(image: AssetImage(ImageConstant.imgGroup561), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildSettingsRow(context), SizedBox(height: 322.v), _buildWeather1(context), SizedBox(height: 299.v), SizedBox(height: 3.v, width: 83.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(width: 83.h, child: Divider())), Align(alignment: Alignment.center, child: SizedBox(width: 83.h, child: Divider()))]))]))), Align(alignment: Alignment.center, child: SizedBox(height: 843.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgImage3512, height: 843.v, width: 390.h, radius: BorderRadius.circular(40.h), alignment: Alignment.center), _buildVectorColumn(context)])))])))), CustomImageView(imagePath: ImageConstant.imgAndroidLarge, height: 843.v, width: 390.h, alignment: Alignment.center)]))))); } 
/// Section Widget
Widget _buildSettingsRow(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgSettingsOnprimarycontainer, height: 8.v, width: 12.h, margin: EdgeInsets.only(top: 3.v, bottom: 4.v)), Container(width: 19.h, margin: EdgeInsets.only(left: 6.h, bottom: 3.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("4G", style: CustomTextStyles.productSansOnPrimaryContainer), Align(alignment: Alignment.centerRight, child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgLine28, height: 1.v, width: 2.h, margin: EdgeInsets.only(top: 2.v)), CustomImageView(imagePath: ImageConstant.imgLine28, height: 3.v, width: 2.h, margin: EdgeInsets.only(left: 1.h))]))]), CustomImageView(imagePath: ImageConstant.imgLine28, height: 6.v, width: 2.h, margin: EdgeInsets.only(left: 1.h, top: 6.v)), CustomImageView(imagePath: ImageConstant.imgLine28, height: 9.v, width: 2.h, margin: EdgeInsets.only(left: 1.h, top: 3.v))])), Spacer(), Text("55%", style: CustomTextStyles.bodyMediumOnPrimaryContainer13), Padding(padding: EdgeInsets.only(left: 4.h, bottom: 3.v), child: SizedBox(height: 11.v, width: 22.h, child: ClipRRect(borderRadius: BorderRadius.circular(5.h), child: LinearProgressIndicator(value: 0.5, valueColor: AlwaysStoppedAnimation<Color>(theme.colorScheme.onPrimaryContainer.withOpacity(0.31)))))), Container(height: 5.v, width: 2.h, margin: EdgeInsets.only(left: 1.h, top: 4.v, bottom: 6.v), decoration: BoxDecoration(borderRadius: BorderRadius.circular(1.h), border: Border.all(color: theme.colorScheme.onPrimaryContainer.withOpacity(1), width: 1.h)))]); } 
/// Section Widget
Widget _buildWeather1(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 4.h, right: 3.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(right: 15.h), child: _buildRecorderColumn(context, userImage: ImageConstant.imgImage35, recorderText: "Weather")), Padding(padding: EdgeInsets.only(left: 15.h, bottom: 97.v), child: _buildRecorderColumn(context, userImage: ImageConstant.imgImage3558x148, recorderText: "Recorder"))])); } 
/// Section Widget
Widget _buildVectorColumn(BuildContext context) { return Align(alignment: Alignment.bottomCenter, child: GestureDetector(onTap: () {onTapVectorColumn(context);}, child: Container(padding: EdgeInsets.symmetric(horizontal: 152.h, vertical: 12.v), decoration: AppDecoration.outlineBlack9005, child: Divider()))); } 
/// Common widget
Widget _buildRecorderColumn(BuildContext context, {required String userImage, required String recorderText, }) { return Expanded(child: SizedBox(width: double.maxFinite, child: Column(children: [CustomImageView(imagePath: userImage, height: 58.v, width: 148.h, radius: BorderRadius.circular(29.h)), SizedBox(height: 3.v), Container(decoration: AppDecoration.outlineBlack900, child: Text(recorderText, style: theme.textTheme.bodySmall!.copyWith(color: theme.colorScheme.onPrimaryContainer.withOpacity(1))))]))); } 
/// Navigates to the mainHomeScreenTwoScreen when the action is triggered.
onTapVectorColumn(BuildContext context) { Navigator.pushNamed(context, AppRoutes.mainHomeScreenTwoScreen); } 
 }
